### ISSUE TITLE
Instructions to Install/Run App?

### ISSUE THREAD

**Issue by program247365** [dvdotsenko/pfkaplr#1]
For those developers out there not familiar with how to run Python/Tornado apps, I'd suggest updating your readme/documentation/website to include that. Also perhaps list what requirements may be needed by someone (installing Tornado, etc.).
1. Cd to the 'src' directory on the commandline and then run the app:

``` bash
python app.py
```
1. Then open up http://localhost:53215/ in a browser.

Thanks!

**Comment by dvdotsenko** [comment]
Github removed "Download" functionality. There is no need to "install" it. I had posted executable that you just double-click.

I will try to set up a "download page" in a day or two. 

Thank you for input.

What platform are you running this on by the way?

**Comment by dvdotsenko** [comment]
A patched (altered HTTP server handler) Tornado server is included in the install. It is changed to work as a relative module, so there is really no prerequisite component for PFKaplr. Just "python" 2.x

**Comment by program247365** [comment]
@dvdotsenko Gotcha.

As I was testing this out, I got it running on Mac OSX (10.7.5). And I was trying to get Virtualbox Windows machines running IE6/7/8/9/10. I'm developing on my Mac, and looking at changes in those IEs. This kind of setup possible?

Or do I have to run it on Windows?

Understood on the tornado thing. That makes sense.

**Comment by dvdotsenko** [comment]
I did not try IE6,7... IE 8 is the lowest IE I have access to.

Still, the scenario you described - Mac host + VirtualBox instances clients is entirely possible. You obviously need the IE plugin for IE lower than 10 (because earlier versions of IE don't have WebSockets - something LiveReload depends on). 

The download link for the plugin was available here https://github.com/dvdotsenko/livereload_ie_extension but GitHub discontinued "Download" feature few weeks ago.

I'll set up new download page (or move the downloads to code.google.com) over the weekend.

Thanks for input.

**Comment by F1LT3R** [comment]
Has anyone integrated this into a Grunt workflow?
